name = "SistemasComplejos"
authors = ["Daniel Luque", "Christian Mu√±oz"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SCUtils = "49baff95-e071-4f3e-92f1-47152cc99b7a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Vicsek = "e586df3f-75db-45ec-bd3b-e0485f1a1eb1"

[compat]
DrWatson = "2.12.1"
julia = "1.8.5"
